Gemfile
Gemfile.lock
app/models/ability.rb
app/models/user.rb
app/views/layouts/application.html.erb
config/environments/development.rb
config/initializers/devise.rb
config/locales/devise.en.yml
config/routes.rb
db/migrate/20190307222521_devise_create_users.rb
db/migrate/20190307222824_add_name_to_user.rb
db/schema.rb
test/fixtures/users.yml
test/models/user_test.rb

Added Devise and CanCanCan, also generated the Devise User model.
https://github.com/plataformatec/devise
https://github.com/CanCanCommunity/cancancan
Devise is for logging people in, passwords etc. (Authentication)
CanCanCan is for what they are allowed to do after they have logged in. (Authorization)
Waiting on an index page/layout so the log in / log out stuff can be added.
Closes #8

Authentication and authorization.

---

app/assets/javascripts/pages.coffee
app/assets/stylesheets/pages.scss
app/controllers/pages_controller.rb
app/helpers/pages_helper.rb
app/views/pages/about.html.erb
app/views/pages/contact.html.erb
app/views/pages/index.html.erb
app/views/pages/meetup.html.erb
config/routes.rb
test/controllers/pages_controller_test.rb

Hey guys, put some elbow grease into this yesterday, super duper ugly but ill improve it as I go along. Also, feel free to message me on tips to improve this :)

Initial Static Pages

---

.gitignore
app/views/layouts/_alerts.html.erb
app/views/layouts/_navbar.html.erb
app/views/layouts/application.html.erb
app/views/pages/about.html.erb
app/views/pages/contact.html.erb
app/views/pages/index.html.erb
app/views/pages/meetup.html.erb
config/routes.rb
package-lock.json
test/controllers/pages_controller_test.rb
test/controllers/posts_controller_test.rb
test/fixtures/users.yml

Added a basic navbar and I missed some things in my previous code reviews.
I'll be a bit more thorough on the next PRs!

Navbar, fix tests and a little page cleanup.

---

app/views/layouts/_footer.html.erb
app/views/layouts/application.html.erb

Super simple footer, let me know what you think, will work on setting up proper link_to paths etc

footer with dead links

---

app/controllers/application_controller.rb
app/controllers/users/confirmations_controller.rb
app/controllers/users/omniauth_callbacks_controller.rb
app/controllers/users/passwords_controller.rb
app/controllers/users/registrations_controller.rb
app/controllers/users/sessions_controller.rb
app/controllers/users/unlocks_controller.rb
app/models/user.rb
app/views/devise/confirmations/new.html.erb
app/views/devise/mailer/confirmation_instructions.html.erb
app/views/devise/mailer/email_changed.html.erb
app/views/devise/mailer/password_change.html.erb
app/views/devise/mailer/reset_password_instructions.html.erb
app/views/devise/mailer/unlock_instructions.html.erb
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_error_messages.html.erb
app/views/devise/shared/_links.html.erb
app/views/devise/unlocks/new.html.erb
app/views/layouts/_navbar.html.erb
app/views/layouts/application.html.erb
config/routes.rb
test/controllers/users_sessions_controller_test.rb
test/fixtures/users.yml

Moar navbar buttons

---

.env.example
README.md
app/models/user.rb
db/migrate/20190312152824_add_role_to_user.rb
db/schema.rb
db/seeds.rb

I added:
- User roles
- An administrative user that can be added by editing the .env file and running `bin/rails db:seed`
- Some details to the README
I'm going to add a ton of issues now :)

Admin user

---

app/controllers/opportunities_controller.rb
app/helpers/opportunities_helper.rb
app/models/event.rb
app/models/opportunity.rb
app/models/user.rb
app/views/layouts/_navbar.html.erb
app/views/opportunities/_form.html.erb
app/views/opportunities/_opportunity.json.jbuilder
app/views/opportunities/edit.html.erb
app/views/opportunities/index.html.erb
app/views/opportunities/index.json.jbuilder
app/views/opportunities/new.html.erb
app/views/opportunities/show.html.erb
app/views/opportunities/show.json.jbuilder
config/routes.rb
db/migrate/20190314192535_create_opportunities.rb
db/schema.rb
test/controllers/opportunities_controller_test.rb
test/fixtures/opportunities.yml
test/models/opportunity_test.rb
test/system/opportunities_test.rb

Added CRUD for opportunities (jobs etc). Closes #34

Add opportunities CRUD

---

.env.example
app/controllers/application_controller.rb
app/controllers/events_controller.rb
app/controllers/users/registrations_controller.rb
app/helpers/application_helper.rb
app/models/ability.rb
app/models/user.rb
app/views/devise/registrations/new.html.erb
app/views/events/index.html.erb
app/views/events/show.html.erb
app/views/layouts/_alerts.html.erb
db/migrate/20190314150837_add_last_name_to_user.rb
db/schema.rb
db/seeds.rb

Our log ins actually do something now... You have to be logged in and an editor or admin to edit events.
I'm unhappy with how Devise is handling the status messages (errors, success etc) and opened an issue.

User roles

---

app/views/devise/registrations/edit.html.erb
app/views/layouts/_navbar.html.erb

Users can view accounts and change passwords.

User accounts

---

.gitignore
Gemfile
Gemfile.lock
test/test_helper.rb

Every time we run a test it will generate a test coverage report, you will be able to see the file location in your terminal after you run the tests!
Closes #21

Add simplecov

---

app/views/layouts/application.html.erb

Hey, just added the viewport to application.html.erb
Let me know if anything else needs to be done with it. :)
closes #22

basic viewport

---

test/controllers/events_controller_test.rb
test/factories.rb

Closes #44 
I added tests for admin and editor

Event tests

---

.rubocop.yml
app/controllers/events_controller.rb
app/controllers/opportunities_controller.rb
app/controllers/sessions_controller.rb
app/controllers/users_controller.rb
app/views/events/_event.json.jbuilder
app/views/events/index.json.jbuilder
app/views/events/show.json.jbuilder
app/views/opportunities/_opportunity.json.jbuilder
app/views/opportunities/index.json.jbuilder
app/views/opportunities/show.json.jbuilder
app/views/users/_user.json.jbuilder
app/views/users/index.json.jbuilder
app/views/users/show.json.jbuilder
config/routes.rb

Closes #32 
Closes #70 
Made flash messages consistent throughout controllers
Eliminated the json.

Flash and json

---

app/models/user.rb
config/routes.rb
test/models/user_test.rb

Closes #72 
It doesn't always annotate the models, but otherwise is good to go. Updated user model.

Annotate user

---

README.md
db/seeds.rb

Makes admin creation a bit clearer

Improved admin creation

---

Gemfile
Gemfile.lock
app/assets/stylesheets/application.scss
app/controllers/events_controller.rb
app/controllers/opportunities_controller.rb
app/views/events/index.html.erb
app/views/opportunities/index.html.erb

We now have pagination for events and opportunities

Add pagination

---

app/assets/stylesheets/application.scss
app/views/events/_event.html.erb
app/views/events/_form.html.erb
app/views/events/edit.html.erb
app/views/opportunities/_form.html.erb
app/views/opportunities/_opportunity.html.erb
app/views/opportunities/edit.html.erb
app/views/opportunities/index.html.erb
app/views/opportunities/show.html.erb
config/routes.rb

Standardized the buttons and made things a wee bit prettier.
closes #41

better buttons

---

app/assets/stylesheets/application.scss
app/controllers/events_controller.rb
app/controllers/opportunities_controller.rb
app/models/ability.rb
app/models/event.rb
app/models/opportunity.rb
app/models/user.rb
app/views/events/index.html.erb
app/views/opportunities/index.html.erb
test/controllers/events_controller_test.rb
test/controllers/opportunities_controller_test.rb
test/factories.rb

Closes #73 
Closes #43 
Closes #48 
Validations, authorisations and tests for events and opportunities

Moar tests

---

app/views/invites/index.html.erb
app/views/invites/new.html.erb
app/views/opportunities/show.html.erb
app/views/sessions/new.html.erb
app/views/users/index.html.erb
app/views/users/new.html.erb
app/views/users/show.html.erb
config/routes.rb

ensure all pages have titles

---

app/controllers/opportunities_controller.rb
app/models/opportunity.rb
app/views/events/_event.html.erb
app/views/opportunities/_form.html.erb
app/views/opportunities/_opportunity.html.erb
config/routes.rb
test/controllers/opportunities_controller_test.rb

Close opportunities

---

app/assets/stylesheets/application.scss
app/controllers/events_controller.rb
app/controllers/invites_controller.rb
app/controllers/pages_controller.rb
app/helpers/sessions_helper.rb
app/models/event.rb
app/models/meetup.rb
app/views/events/_event.html.erb
app/views/layouts/_footer.html.erb
app/views/layouts/_navbar.html.erb
app/views/opportunities/_form.html.erb
app/views/opportunities/_opportunity.html.erb
app/views/pages/about.html.erb
app/views/pages/aboutus.html.erb
app/views/pages/contact.html.erb
app/views/pages/getinvolved.html.erb
app/views/pages/index.html.erb
app/views/pages/opportunities.html.erb
app/views/pages/resources.html.erb
app/views/pages/slack.html.erb
config/routes.rb
lib/tasks/dbfill.rake
test/controllers/events_controller_test.rb
test/controllers/opportunities_controller_test.rb
test/controllers/pages_controller_test.rb
test/factories.rb

Big functionality additions around events

Upcoming events

---

app/models/meetup.rb
config/environments/test.rb

Enable caching for tests, looked at using VCR as an alternative but it would mean some mocking... which I don't want to do unless completely necessary!

test caching

---

app/assets/stylesheets/application.scss
app/views/events/_event.html.erb
app/views/events/_form.html.erb
app/views/events/index.html.erb
app/views/invites/index.html.erb
app/views/invites/new.html.erb
app/views/layouts/_footer.html.erb
app/views/layouts/_navbar.html.erb
app/views/layouts/application.html.erb
app/views/opportunities/_form.html.erb
app/views/opportunities/_opportunity.html.erb
app/views/opportunities/index.html.erb
app/views/pages/getinvolved.html.erb
app/views/pages/index.html.erb
app/views/sessions/new.html.erb
app/views/users/_form.html.erb
app/views/users/index.html.erb
app/views/users/show.html.erb

Lots of @extend and removing crufty code. We no longer have as many classes cluttering up our html.

Cleaned up bootstrap and sass

---

app/models/event.rb
app/views/events/_event.html.erb

Our addresses auto magically have Google Maps links.

google maps link

---

app/assets/stylesheets/application.scss
app/controllers/events_controller.rb
app/controllers/opportunities_controller.rb
app/models/event.rb
app/models/opportunity.rb
app/views/events/_event.html.erb
app/views/events/_form.html.erb
app/views/events/_nav.html.erb
app/views/events/index.html.erb
app/views/events/new.html.erb
app/views/opportunities/_form.html.erb
app/views/opportunities/_nav.html.erb
app/views/opportunities/_opportunity.html.erb
app/views/opportunities/index.html.erb
app/views/opportunities/new.html.erb

we now have submenus

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/stylesheets/application.scss
app/models/event.rb
app/models/opportunity.rb
app/views/events/_form.html.erb
app/views/events/_form_help.html.erb
app/views/opportunities/_form.html.erb
app/views/opportunities/_form_help.html.erb

We have datetime pickers, help section etc now.
Closes #122

Better forms

---

app/assets/stylesheets/application.scss
app/views/events/_event.html.erb
app/views/layouts/_navbar.html.erb
app/views/opportunities/_opportunity.html.erb
app/views/pages/index.html.erb

font-awesome

---

app/assets/stylesheets/application.scss
app/views/layouts/_navbar.html.erb

Surprisingly difficult, but I think it looks nice now.
Navbar shows active page now.

made navbar 2 columns

---

app/controllers/invites_controller.rb
app/controllers/users_controller.rb
app/models/invite.rb
app/views/invites/_invite.html.erb
app/views/invites/index.html.erb
app/views/invites/new.html.erb
app/views/users/_user.html.erb
app/views/users/index.html.erb

Made things more compact, attractive, and dry. Added pagination.

nicer admin interface

---

app/assets/stylesheets/application.scss
app/controllers/sessions_controller.rb
app/helpers/sessions_helper.rb
app/models/opportunity.rb
app/models/user.rb
app/views/sessions/new.html.erb
db/migrate/20190415065244_add_remember_digest_to_users.rb
db/schema.rb
test/controllers/opportunities_controller_test.rb
test/controllers/sessions_controller_test.rb
test/models/user_test.rb

Closes #81 
Persists users so they don't have to log in again every time they return to the site (unless they log out)

remember user

---

app/models/event.rb
app/models/user.rb
test/controllers/events_controller_test.rb
test/controllers/sessions_controller_test.rb
test/controllers/users_controller_test.rb

Closes #95 
A user can now edit their user profile without changing their password. Added additional tests.

conditional password validation

---

app/controllers/events_controller.rb
app/controllers/invites_controller.rb
app/controllers/opportunities_controller.rb
app/controllers/users_controller.rb
test/controllers/events_controller_test.rb
test/controllers/opportunities_controller_test.rb

cancancan coverage and tests

---

app/models/event.rb

Closes #117 . Found a small issue with order of upcoming events.

checked scopes

---

Gemfile
Gemfile.lock
app/assets/stylesheets/application.scss
app/helpers/application_helper.rb
app/views/events/_event.html.erb
app/views/opportunities/_opportunity.html.erb

add markdown

---

.env.example
app/views/pages/resources.html.erb

Just added a link for a newbie resource

added link

---

app/assets/stylesheets/application.scss
app/views/messages/_form.html.erb

Use placeholders instead of labels, shrink the envelope icon, and change "Email Alan" to "Email Andy and Will"

Tidy up contact form
